version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: appang-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - appang-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: appang-redis
    ports:
      - "6379:6379"
    volumes:
      - appang-redis-data:/data


  backend:
    image: cshoney/appang-backend:latest
    container_name: appang-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_KEY}
    depends_on:
      - db
      - redis

  nginx:
    image: cshoney/appang-frontend:latest
    container_name: appang-nginx
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  appang-data:
  appang-redis-data: