version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: appang-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - appang-data:/var/lib/mysql
  backend:
    build: .
    container_name: appang-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  appang-data: